### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by bhstark2** [bhstark2/babel-information-model#1]
What I'd like to do for logging:
delete security-obj babel-credvalid-log-enable
delete security-obj babel-credvalid-log
delete interfaces-obj babel-message-log
move interfaces-obj babel-message-log-enable to information-obj
add to information-obj [string    babel-message-log]: A reference or url link to a file that contains a timestamped log of messages received and sent on babel-udp-port on all interfaces. File format MUST be readable by Wireshark 1.8 or later and use the applicable file format extension in the filename. Logging is enabled / disabled by babel-message-log-enable.
Would this work for YANG?
Need to confirm with implementers that this would make sense for them.

**Comment by mjethanandani** [comment]
This makes sense to me.

**Comment by bhstark2** [comment]
I think logging is done.
