### ISSUE TITLE
babel-interface-metric-algorithm is defined as a string

### ISSUE THREAD

**Issue by mjethanandani** [bhstark2/babel-information-model#10]
In Section 3.3, babel-interface-obj, babel-interface-metric-algorithm is defined as a string. However, the description says it MUST be one of the babel-metric-comp-algorithms. Shouldn't the type then be babel-metric-comp-algorithms?

**Comment by bhstark2** [comment]
babel-metric-comp-algorithms isn't a type. The types are described in section 1.2, and I don't think we want to be creating types for every enumerated list that constrains an enumerated parameter. babel-metric-comp-algorithms is a list of strings. So any parameter that is constrained to one of the strings in that list must also be a string. In TR-181 I define babel-metric-comp-algorithm as a string, but constrain its value to existing in babel-metric-comp-algorithms.

**Comment by mjethanandani** [comment]
Agree that babel-metric-comp-algorithm is not one of the base types defined in Section 1.2. What I mean is that babel-metric-comp-algorithms is a list of well defined algorithms, two of which you cite in the draft - “k-out-of-j”, and “ETX”. However you encode them, an implementation will look at them as two different *types* of algorithms, and assign them two different values, say 1 for “k-out-of-j”, and 2 “ETX”. Would it not be easier if they were defined such that they could be given those values to begin with, instead of allowing a string, which then has to be checked for constrains and then converted to a value?

**Comment by bhstark2** [comment]
Hmm. In TR-181 they're just (constrained, enumerated) strings. What you describe is a way for an implementation to deal with them. But not the only way. I was looking at the babeld code (https://github.com/jech/babeld) configuration.h and configuration.c and I see string manipulation for link type stuff. 
But I don't see where defining them as strings in the info-model prevents you from modeling them in YANG the way you have. I think the YANG modeling is a good use of YANG data types and is not inconsistent with the info-model.
If you think it's a problem, I'd be willing to consider something less well defined. Like having an info-model "enumeration" data type that is an enumerated value (or list of enumerated values).

**Comment by jech** [comment]
J-out-of-k is a family of algorithms, parameterised by two integers j and k.  Babeld uses 2-out-of-3 in the case of wired links.

**Comment by bhstark2** [comment]
Left these as string data types in info-model, references in YANG model, and changed j-out-of-k enumeration to 2-out-of-3.
