### ISSUE TITLE
Reference to babel-unicast-hello-seqno and babel-unicast-hello-interval

### ISSUE THREAD

**Issue by mjethanandani** [bhstark2/babel-information-model#11]
The two attributes do not exist in the latest version. Why then refer to them in the description for babel-update-interval?

**Comment by bhstark2** [comment]
I'm not finding this reference?
babel-update-interval says: The current interval in use for all updates (multicast and unicast) sent on this interface. Units are centiseconds. This is a 16-bit unsigned integer.
I do find the following 2 parameters (in the overview, in babel-neighbors-obj, and description under babel-neighbors-obj): babel-ucast-hello-seqno, babel-ucast-hello-interval
I don't find babel-unicast-hello-seqno or babel-unicast-hello-interval mentioned anywhere.
In any case, the unicast Hello seqno and interval should have no impact on update interval, so I wouldn't expect a reference to these Hello parameters from babel-update-interval.
