### ISSUE TITLE
Non empty/null parameters

### ISSUE THREAD

**Issue by bhstark2** [bhstark2/babel-information-model#14]
There are some parameters that must not be null or empty when written. This can be ensured either by requiring a non-empty value when writing to it, or having a default defined for use when the written value is empty or the parameter is not present in the data provided by the management system. While the info model can state when a parameter cannot be null/empty, it may be better for a specific data model to decide whether this is done by using a default or requiring the parameter to be present and non-empty/null. Where defaults or known, the info model needs to provide them.

All rw parameters need to be assessed as to whether they have a default, can be empty, and whether a change is needed to the current text.

rw parameters and proposed resolutions
-----------------------------------------

1. Boolean parameters inside r objects: not possible to write an empty value; parameters inside ro objects (babel-enable, babel-stats-enable, babel-interface-enable, babel-packet-log-enable) will be created by the Babel implementation, so no info-model-specified default is needed for an object instance created by the management system; the Babel implementation needs to decide what the right default is for when it creates the parameter; no change proposed
3. Boolean parameters inside rw objects: not possible to write an empty value; these parameters (babel-hmac-verify, babel-hmac-apply-all, babel-hmac-key-use-sign, babel-hmac-key-use-verify, babel-dtls-apply-all, babel-dtls-cached-info) should be dealt with by each data model (or even Babel implementation)  as to whether to default them -- and what the default should be -- or require them to be present
5. babel-udp-port, babel-mcast-group: have defaults defined; no proposed changes
7. babel-link-type, babel-hmac-algorithm, babel-cert-type: no change proposed because the value is already required to be one of the enumeration values
9. babel-hmac-key-name: currently ro, but description suggests rw, and it cannot be empty; proposed modifications in bold: A unique name for this HMAC key that can be used to identify the key in this object instance, since the key value is not allowed to be read. This value **MUST NOT be empty and** can only be provided when this instance is created **(i.e., it is not subsequently writable). The value MAY be auto-generated if not explicitly supplied when the instance is created.**
12. babel-hmac-interfaces, babel-dtls-interfaces: can be empty (as denoted by <0..*>); no change proposed
14. babel-cert-private-key: can be empty; no change proposed
16. babel-hmac-key-value, babel-cert-value: cannot be empty when written; proposed change in bold to last sentence: "This value **MUST** be provided when this instance is created, and is not subsequently writable.
18. babel-hmac-key-test and babel-cert-test input string: cannot be empty; no default; proposed change in bold to 2nd sentence: "Input to this operation **MUST be a non-empty** binary string."

**Comment by bhstark2** [comment]
I see that I didn't do the changes noted in bold in the proposed resolutions above. I think they're still needed.

**Comment by bhstark2** [comment]
Changes in bold still need to be done.

**Comment by mjethanandani** [comment]
In general I believe that we should make a concerted effort to come up with default values for rw objects, especially those that are mandatory to specify. It helps management systems if default values are specified and every system does not have to provide one. Worst case, if the system does not agree with the default value, they can override it.

For example, for interface enable flag, I have defaulted to "true", and under interface for link-properties to "wired", for metric-algorithm "k-out-of-j". 

Want to bring them up in WG meeting for discussion, so feel free to add to this list.

**Comment by bhstark2** [comment]
Item 5 in list was done in -08. Items 8 and 9 were done as described in -08 but overtaken by events in -09.
