### ISSUE TITLE
Why is babel-dtls-cert-prefer not a reference?

### ISSUE THREAD

**Issue by mjethanandani** [bhstark2/babel-information-model#19]
The description for the property says that the value MUST be among those listed in the babel-dtls-cert-types parameter. In that sense is it not the same as babel-interface-dtls-certs or dtls-hmac-algorithms which are also references.

**Comment by bhstark2** [comment]
babel-hmac-algorithm is currently a string data type.
This is another case where TR-181 and YANG are different in how they model this. I see in YANG that this will be modeled using instance-identifier, which is type of reference. In TR-181, it's a string whose value is constrained to be among those of the list (which is referenced from the syntax definition), but the value itself isn't a reference.
I didn't use "reference" info model data type for any of these (babel-interface-metric-algorithm, babel-hmac-algorithm, babel-cert-type, and probably some others) that are constrained by the contents of what in YANG would be a leaf-list.
I guess I don't care if we change the reference data type to include this sort of thing, but I'd need to include that in the description of the reference data type and change it for all of these. It won't change how I model it in TR-181.

**Comment by bhstark2** [comment]
string in info model but reference in YANG is ok
