### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by bhstark2** [bhstark2/babel-information-model#2]
For statistics:
The proposed parameters (from Bangkok slides) are:
Under interfaces-obj: sent multicast Hello, sent updates, received Babel messages
Under neighbors-obj: sent unicast Hello, sent updates, sent IHU, received Hello, received updates, received IHUs.  
Would also need to enable/disable stats and clear stats.

I'd like to put these in their own single instance object underneath the 2 mentioned objects.

**Comment by bhstark2** [comment]
Done

**Comment by mjethanandani** [comment]
I know you have closed this issue, but I am curious whey anyone would need to enable/disable collection of stats. An implementation may choose whether to implement collection of stats, but if collected, one can choose not to read them. But why disable them?

**Comment by bhstark2** [comment]
I've seen logs and statistics collection cause performance issues on some resource-constrained Wi-Fi routers. But if we don't think collection of these statistics are ever likely to cause performance issues, then I'm fine getting rid of the "enable" parameter. Or move it up to the top level so it's just a single parameter to globally enable/disable statistics collection.
