### ISSUE TITLE
Nits and other little needed changes

### ISSUE THREAD

**Issue by bhstark2** [bhstark2/babel-information-model#7]
This issue is being used to track known nits that need updating.

Delete RFC3986 reference (idnits noticed this wasn't referenced).
Delete "Interface: External cost (must be configurable if implemented, but implementation is optional)" from overview list of non-read-only parameters. This parameter no longer exists.
Delete Appendix A and Appendix B.
Change "hellos" to "Hellos" (2 instances).
Can we get better description of what caclulated/received-metric are used for?

**Comment by jech** [comment]
I suggest not using a single github issue for multiple issues.

> Can we get better description of what caclulated/received-metric are used for?

This is described in Section 3.5.2 of RFC 6126bis.

Let A and B be neighbours.

B announces a route with metric mB.  A receives the route and goes « hey, cool, B knows how to reach the destination with a cost mB », and computes a value mA > mB by combining mB with the cost of the link.  At which point it says « I know how to reach the destination with cost mA ».

From A's perspective, mB is the metric it received, while mA is the metric it calculated.

**Comment by bhstark2** [comment]
All nits are fixed in updated draft.
